version: '3'
services:
  nginx-project2:
    container_name: ${CONTAINER_NGINX_PROJECT_NAME}
    image: ${NGINX_PROJECT_IMAGE}:${NGINX_PROJECT_IMAGE_VERSION}
    user: root
    restart: "unless-stopped"
    hostname: "nginx-project2"
    depends_on:
      - php-fpm-project2
    networks:
      proxy:
        ipv4_address: ${CONTAINER_NGINX_PROJECT_IPV4}
    ports:
      - ${CONTAINER_NGINX_PROJECT_PORT:-6080}:6080
    expose:
      -  ${CONTAINER_NGINX_PROJECT_PORT:-6080}
    dns: 8.8.8.8
    volumes:
      - ${PHP_APP_PROJECT_DIR}:${BITNAMI_PHP_APP_DIR}
      - ${NGINX_CONF_PROJECT_FILE}:${BITNAMI_NGINX_CONF_PROJECT_FILE}:ro
      - /usr/share/zoneinfo/Europe/Amsterdam:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${NGINX_LOGS_PROJECT_FILE}:/opt/bitnami/nginx/logs
    environment:
      - BITNAMI_DEBUG=true
      - VIRTUAL_HOST=${MAIN_DOMAIN_PROJECT}
      - VIRTUAL_PORT=${CONTAINER_NGINX_PROJECT_PORT:-6080}
      - LETSENCRYPT_HOST=${MAIN_DOMAIN_PROJECT}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: ${LOGGING_NGINX_OPTIONS_MAX_SIZE:-100m}
  php-fpm-project2:
    container_name: ${CONTAINER_PHPFPM_PROJECT_NAME}
#    image: ${PHP_PROJECT_IMAGE}:${PHP_PROJECT_IMAGE_VERSION}
    build:
      context: .
      dockerfile: ${PHP_PROJECT_DOCKERFILE}
      args:
        IMAGE: ${PHP_PROJECT_IMAGE}
        TAG: ${PHP_PROJECT_IMAGE_VERSION}
        PORT: ${CONTAINER_PHPFPM_PROJECT_INTERNAL_PORT:-9000}
    restart: "unless-stopped"
    hostname: "php-fpm-project2"
    networks:
      proxy:
        ipv4_address: ${CONTAINER_PHPFPM_PROJECT_IPV4}
    ports:
      - ${CONTAINER_PHPFPM_PROJECT_PORT:-9002}:${CONTAINER_PHPFPM_PROJECT_INTERNAL_PORT:-9000}
    expose:
      - ${CONTAINER_PHPFPM_PROJECT_INTERNAL_PORT:-9000}
    volumes:
      - ${PHP_APP_PROJECT_DIR}:${BITNAMI_PHP_APP_DIR}
      - ${PHP_CONF_PROJECT_FILE}:${BITNAMI_PHP_CONF_FILE}:ro
      - ${PHP_EXT_PROJECT_DIR}:${BITNAMI_PHP_EXT_DIR}:ro
      - ${PHP_INI_PROJECT_DIR}/php.ini:${BITNAMI_PHP_INI_DIR}/php.ini
      - /usr/share/zoneinfo/Europe/Amsterdam:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PHP_INI_SCAN_DIR=${BITNAMI_PHP_INI_SCAN_DIR}
      - RUN_SCRIPTS=1
      - REAL_IP_HEADER=1
      - ERRORS=1
      - BITNAMI_DEBUG=true
    logging:
      options:
        max-size: ${LOGGING_PHP_OPTIONS_MAX_SIZE:-100m}
  wkhtmltopdf2:
    container_name: ${CONTAINER_WKHTMLTOPDF_NAME:-wkhtmltopdf2}
    build:
      context:  ${WKHTMLTOPDF_DOCKERFILESDIR}
      dockerfile: ./Dockerfile2
      args:
        IMAGE: ${WKHTMLTOPDF_IMAGE}
        TAG: ${WKHTMLTOPDF_IMAGE_VERSION}
        PORT: ${CONTAINER_WKHTMLTOPDF_INTERNAL_PORT}
    restart: "unless-stopped"
    hostname: "wkhtmltopdf2"
    ports:
      - ${CONTAINER_WKHTMLTOPDF_PORT:-4001}:${CONTAINER_WKHTMLTOPDF_INTERNAL_PORT:-4001}
    expose:
      - ${CONTAINER_WKHTMLTOPDF_INTERNAL_PORT:-4001}
    volumes:
      - ${PHP_APP_PROJECT_DIR}:${BITNAMI_PHP_APP_DIR}
      - /usr/share/zoneinfo/Europe/Amsterdam:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      proxy:
        ipv4_address: ${CONTAINER_WKHTMLTOPDF_IPV4}
networks:
  proxy:
    external:
      name: ${NETWORK}

